{% set name = "absl-py" %}
{% set version = "1.4.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d2c244d01048ba476e7c080bd2c6df5e141d211de80223460d5b3b8a2a58433d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  # The package absl is not available in s390x.
  skip: True  # [py<36 or s390x]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - absl
    - absl.flags
    - absl.logging
    - absl.testing
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://abseil.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    This repository is a collection of Python library code for building Python applications. 
    The code is collected from Google's own Python code base,
    and has been extensively tested and used in production.
  doc_url: https://abseil.io/docs/python/
  dev_url: https://github.com/abseil/abseil-py
  doc_source_url: https://github.com/abseil/abseil-py/blob/main/docs/source/

extra:
  recipe-maintainers:
    - jjhelmus
