{% set name = "absl-py" %}
{% set version = "0.14.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7675ddb70ffd0e37a2e69322f8f2cd37b19e03a27f43420bea5850597ded9504" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - absl
    - absl.flags
    - absl.logging
    - absl.testing
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://abseil.io/
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
  doc_url: https://abseil.io/docs/
  dev_url: https://github.com/abseil/abseil-py

extra:
  recipe-maintainers:
    - jjhelmus
