{% set name = "absl-py" %}
{% set version = "0.4.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "932e6acb1a57bdcfb784a1ce6ad46a2f50b89d355a5619ed6df60db1414173d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  noarch: {{ noarch_python }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - absl
    - absl.flags
    - absl.logging
    - absl.testing

about:
  home: https://abseil.io/
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
  doc_url: https://abseil.io/docs/
  dev_url: https://github.com/abseil/abseil-py

extra:
  recipe-maintainers:
    - jjhelmus
