{% set name = "absl-py" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: a97820526f7fbfd2ec1bce83f3f25e3a14840dac0d8e02a0b71cd75db3f77fc9

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv 

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - hatchling >=1.26
  run:
    - python

test:
  imports:
    - absl
    - absl.flags
    - absl.logging
    - absl.testing
  requires:
    - pip
  commands:
    - pip check
  
about:
  home: https://abseil.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Abseil Common Libraries (Python)
  description: |
    This repository is a collection of Python library code for building Python applications. 
    The code is collected from Google's own Python code base,
    and has been extensively tested and used in production.
  doc_url: https://abseil.io/docs/python/
  dev_url: https://github.com/abseil/abseil-py

extra:
  recipe-maintainers:
    - jjhelmus
